spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: employee
    password: employee
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

show-sql: true
