version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: pg-emp
    restart: unless-stopped
    environment:
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: employee
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: